services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: nti
      POSTGRES_PASSWORD: ntipassword
      POSTGRES_DB: nti_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nti -d nti_db"]
      interval: 2s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - uploads:/app/uploads
    env_file:
      - .env

volumes:
  pgdata:
  uploads:
