"""add_program_categories

Revision ID: 0c83ed8a9a2d
Revises: b6649a1159e3
Create Date: 2026-06-21 15:53:19.282547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c83ed8a9a2d'
down_revision: Union[str, Sequence[str], None] = 'b6649a1159e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'categories')
    # ### end Alembic commands ###
